#164576233 - Setup Dashboard page
andela/denethor-ah-frontend pull request #19
Opened 2019-03-14 20:29 UTC by jsamchineme

###  What this PR does
- Allow users access a dashboard after login
- Implement articles listing on dashboard
- write tests for the dashboard component

### How to test
- Clone this branch
- signup and/or login
- From sidebar on dashboard, click top reads to view article listing

### Screenshots

![image](https://user-images.githubusercontent.com/14825863/54385262-7c8a7c00-4696-11e9-8b07-f0069969230d.png)

### Relevant pivotal tracker stories
https://www.pivotaltracker.com/story/show/164576233

2019-03-15 06:57 UTC, omoefe-dukuye reviewed
@jsamchineme Great job man. Loving the dark theme. Though it seems the logic in the `componentDidMount()` hook that exists in `Dashboard.jsx` on staging seems to be missing from your work.

2019-03-17 08:23 UTC, ifiokeyo requested changes

2019-03-17 08:23 UTC, ifiokeyo commented on src/components/comments/CommentEntries.jsx
> +import { LikeNumberGroup } from '../../components/like-button';
@jsamchineme Javascript adopts the camelcase pattern for filenames, directory names, variables, etc. Please change `lines 4 and 5` to use this pattern.

2019-03-17 08:23 UTC, ifiokeyo commented on src/components/dashboard/Dashboard.jsx
> +import { TopReads } from '../articles/top-reads';
@jsamchineme see above comment.

2019-03-17 08:23 UTC, ifiokeyo commented on src/components/dashboard/Dashboard.jsx
> +      <div className={`dashboard-page-wrapper`}>
@jsamchineme why is the `className` reference this way ?

2019-03-20 18:25 UTC, closed without merging